# This file tells netlify where the code for this project is and
# how it should build the JavaScript assets to deploy from.
[build]
  base = "frontend/"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200